# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:18.1.0"
  amd64: "ghcr.io/hassio-addons/base/amd64:18.1.0"
  armhf: "ghcr.io/hassio-addons/base/armhf:18.1.0"
  armv7: "ghcr.io/hassio-addons/base/armv7:18.1.0"
  i386: "ghcr.io/hassio-addons/base/i386:18.1.0"
labels:
  org.opencontainers.image.title: "Doorbell Face Recognition"
  org.opencontainers.image.description: "AI-powered doorbell with face recognition capabilities"
  org.opencontainers.image.source: "https://github.com/Beast12/whorang"
  org.opencontainers.image.version: "1.0.0"
  org.opencontainers.image.authors: "Beast12"
  org.opencontainers.image.licenses: "MIT"
args:
  DOORBELL_VERSION: "1.0.0"
